AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: >
  python-serverless-api
  API REST serverless com Python, Lambda, API Gateway e PostgreSQL

Globals:
  Function:
    Runtime: python3.11
    Timeout: 30
    MemorySize: 128
    Environment:
      Variables:
        DB_HOST:     !Ref DBHost
        DB_NAME:     !Ref DBName
        DB_USER:     !Ref DBUser
        DB_PASSWORD: !Ref DBPassword
        DB_PORT:     "5432"

  Api:
    Auth:
      DefaultAuthorizer: CognitoAuthorizer
      Authorizers:
        CognitoAuthorizer:
          UserPoolArn: !Sub "arn:aws:cognito-idp:sa-east-1:351395890880:userpool/sa-east-1_AvKUaGWO8"
          
Parameters:
  DBHost:
    Type: String
  DBName:
    Type: String
    Default: python_serverless_api
  DBUser:
    Type: String
  DBPassword:
    Type: String
    NoEcho: true

Resources:

  UsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: python-serverless-api-users
      CodeUri: src/
      Handler: handlers.users.lambda_handler
      Description: CRUD de usuários
      Events:

        ListUsers:
          Type: Api
          Properties:
            Path: /users
            Method: GET

        CreateUser:
          Type: Api
          Properties:
            Path: /users
            Method: POST

        GetUser:
          Type: Api
          Properties:
            Path: /users/{id}
            Method: GET

        UpdateUser:
          Type: Api
          Properties:
            Path: /users/{id}
            Method: PUT

        DeleteUser:
          Type: Api
          Properties:
            Path: /users/{id}
            Method: DELETE

Outputs:
  ApiUrl:
    Description: URL base da API
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"

  UsersFunction:
    Description: ARN da função Lambda
    Value: !GetAtt UsersFunction.Arn